[features]
seeds = true

[workspace]
members = ["programs/graph_program"]

[programs.localnet]
graph_program = "grphAFGNvCjLKHeEmPNa91eGJChcUhrdaYYharcZCTQ"

[programs.devnet]
graph_program = "grphAFGNvCjLKHeEmPNa91eGJChcUhrdaYYharcZCTQ"

[programs.mainnet]
graph_program = "grphAFGNvCjLKHeEmPNa91eGJChcUhrdaYYharcZCTQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
